server:
  port: 15000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:12000/spzx?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Wzh@123..
    
  data:
    redis:
      host: localhost
      port: 6379

# 添加 mybatis-plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*/*.xml

# -------------------------------------- 自定义配置 ---------------------------------------- #

custom:
  auth:
    # 不需要拦截的URL
    exclude-urls:
      - /admin/system/index/login
      - /admin/system/index/captcha

